### ISSUE TITLE
Do we have "GnomeHorde" opengl demo?

### ISSUE THREAD

**Issue by ChaithanyaSingamala** [powervr-graphics/Native_SDK#13]
In SDK, I don't find "GonmeHorde" opengl demo, Is this not available or missed?

**Comment by senthuran-lkn** [comment]
GnomeHorde demo is Vulkan only. The purpose of this demo is to show how to do multi-threading in vulkan to improve the rendering performance.

**Comment by ChaithanyaSingamala** [comment]
Thanks for reply, Yes, I understand that.
I see from this blog, https://www.imgtec.com/blog/gnomes-per-second-in-vulkan-and-opengl-es/
equivalent Gnome demo in opengl, so I asked.

I'm also creating demo which try to demonstrate advantage of using multithreading in vulkan over opengl. 
With my demo, when vulkan is giving better performance when there is very high draw calls or state switches(which in case of vulkan recording it into command buffer and submitting).
Else I find opengl giving better performance than vulkan(as I expected to get both same performance).

Any suggestions?

**Comment by PVRDevTech** [comment]
Hi, 

I'm not sure I fully understand your problem, are you saying that you are seeing better performance in OGLES over Vulkan when you only have a small number of draw calls? In what scenario are you seeing better performance in OGLES over Vulkan?
 
Also I will just say that Vulkan is not always guaranteed to be faster than OGLES, it highly depends on how you are using the APIs (indeed Vulkan is a more efficient API and in theory you should be getting better performance); in addition the Gnome Horde demo is just one example of how you can leverage the Vulkan API to perform certain tasks much more efficiently than with the OGLES API.

Kind Regards,
Shaun

**Comment by ChaithanyaSingamala** [comment]
Hi, Thanks for reply.
"seeing better performance in OGLES over Vulkan when you only have a small number of draw calls"
Yes, that what I observed. 
Case when there is no textures switches, no state changes(blend etc) , 
1 tile = 100 different mesh in that tile rendered.
In opengl, no threading and each tile rendered in for loop calling draw calls.
In vulkan, using same Gnome example threading,  each tile( 100 draw calls) are recorded into secondary command buffer and submitted to  primary command buffer
CaseA: 1 tile visible, 100 draws calls - opengl giving better performance
CaseB: 100 tiles visible, 100,000 draw calls - vulkan giving better performance

CaseB gain I can understand as there is CPU->GPU overhead which in case of Vulkan advantage. But in case of CaseA, I expect performance of opengl and vulkan should be same.
(Note I m using SDK 4.2 branch, but I assume that doesn't matter in this case.)

**Comment by senthuran-lkn** [comment]
first of all i assume you have ported  the vulkan example for es and doing a comparison with the same workload. if so i would like to see your code for both es and vulkan (if you modified anything).

**Comment by ChaithanyaSingamala** [comment]
Hi Thanks for your support.,
I have updated source in my git repo, https://github.com/ChaithanyaSingamala/PowerVR_SDK.git with branch "4.2_testing". Can you please check from there or should I create "pull request".

Regarding source, I have creating demo by using Gnome as base and modified it, for sharing I have removed lot of in-house assets so demo will have some missing elements.
As I started with 4.2, hardcoded few places in 4.2 framework for multisampling(I need to shift to 4.3).

I have modified demo for quickly test different cases. Uses keys 'A', 'S' , 'D' , 'F' , 'G' for different zoom levels. Different zoom levels results change in visible tiles.
For me when zoom level at 'A'(5 tiles visible) and 'S'(4 tiles visible) OpenGL give better performance.

**Comment by PVRDevTech** [comment]
Hi,

I ran your demo applications on my local machine and I found that the Vulkan demo runs significantly faster (~5.5x) in cases 'A' and 'S' compared to the OGLES demo. 

Just for reference I was running the demo on a Nvidia GTX 950 GPU, with an Intel i5 (2 cores, 4 threads) CPU. What is the setup of the system are you running the application on?

Thanks,
Shaun

**Comment by senthuran-lkn** [comment]
One thing I recommend is to enable the Vulkan layers on the release build and see if the layers are issuing any errors or performance warning. I will take quick look at your source.

**Comment by ChaithanyaSingamala** [comment]
Hi,
I'm running on embedded target,
Freescale imx.8, GPU is Vivante gc7000
Linux armv8-64bit,
creating 4 threads,

I also tested with Renesas RCarH3 (GPU PowerVR Series6XT GX6650) but here test case modified( made complex to avoid performance caps by VSync).

But did you review ported GLSL project? Any comments on that? Is this correct project to compare with Vulkan and OpenGL?

**Comment by ChaithanyaSingamala** [comment]
Hi, unfortunately target having some issue enabling validation layers. so I cannot check.

**Comment by senthuran-lkn** [comment]
the ES demo is pretty simple with for-loops, its seems fine. I'm reviewing the VK version and see if there is anything strange. Meanwhile it would be useful  if either of us can run it on desktop and check the validation layer.  At the time of writing this demo we didn't had any validation issues, but since then the layers are much more improved, so there might be a catch for this. I will have quick discussion with the team. If I have to build it for Linux I don't need any additional make arguments do i?

**Comment by ChaithanyaSingamala** [comment]
For building for linux you need to specify platform,
make PLATFORM=Linux_armv8_64

**Comment by senthuran-lkn** [comment]
OK, By running it on the  Ubuntu desktop I get the following issues. The first 2 are coming from the framework, which I can fix but the the last one seems like an application issue. 
**DS(WARN): object: 0x1b323a0 type: 6 location: 2032 msgCode: 10: Dest AccessMask 0 [None] must have required access bit 32768 [VK_ACCESS_MEMORY_READ_BIT]  when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, unless the app has previously added a barrier for this transition.**
**DS(WARN): object: 0x1b323a0 type: 6 location: 2032 msgCode: 10: Dest AccessMask 0 [None] must have required access bit 32768 [VK_ACCESS_MEMORY_READ_BIT]  when layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR, unless the app has previously added a barrier for this transition.
SC(ERROR): object: 0x0 type: 3 location: 1758 msgCode: 3: Vertex shader consumes input at location 2 but not provided**

**Comment by senthuran-lkn** [comment]
The warning is fixed in 4.3 branch, commit title "Fixed VkAccessFlag for Presentation Layout"

**Comment by PVRDevTech** [comment]
Hi,

I think the VK layer error: **SC(ERROR): object: 0x0 type: 3 location: 1758 msgCode: 3: Vertex shader consumes input at location 2 but not provided** is due to the app missing the models UVs, this message is printed by the framework when I run the VK demo: **ERROR: Could not find Attribute with Semantic UV0 in the supplied mesh. Will render without binding it, erroneously.** So the framework is continuing to render the frame without the data bound to location 2 in your vertex shader.

So maybe the POD you are using is missing UVs?

This line: **layout(location = 2) in highp vec2 in_uvs;** is in the VK vertex shader, so I think what is happening is that no data is being supplied to this attribute before drawing which is causing the VK layer error.

Thanks,
Shaun
