### ISSUE TITLE
PVRTexTool produces seams on PVR compressed Cube map

### ISSUE THREAD

**Issue by sasmaster** [powervr-graphics/Native_SDK#14]
Iphone 6 . OpenGL ES3.0

**Comment by sasmaster** [comment]
PVR SDK PVR loader uses GL_LINEAR_MIPMAP_NEAREST  for mipmapped textures.I changed to GL_NEAREST_MIPMAP_NEAREST and there are no seams .But I doubt this is normal behavior. The ES3.0 specs say that the CUBE_MAP target guarantees to produce no artifacts on the edges.And indeed that's the case with non compressed textures.

**Comment by sasmaster** [comment]
Discard the message above.Here is the setup which I currently use to get rid of the seams:

                ```
  glTexParameteri(targetOut, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_NEAREST);
                    glTexParameteri(targetOut, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
```

Anything with LINEAR causes the seams right now.

**Comment by PVRDevTech** [comment]
I assume this is no longer relevant. However, in case this is still relevant, this would be a driver issue which we do not control on these platforms.
