### ISSUE TITLE
pvrtexture::GenerateMIPMaps() fails to generate

### ISSUE THREAD

**Issue by sasmaster** [powervr-graphics/Native_SDK#17]
I am loading a texture data from tga image file.Sizes 512x512 ,RGB 8 bit per channel.The texture is correct both on load and on save without mipmaps generation.However, when I try to do this:

       ```
   pvrtexture::CPVRTextureHeader header1(pvrtexture::PVRStandard8PixelTypeRGB.PixelTypeID, height, width);
	  pvrtexture::CPVRTexture texture(header1, imageData);
          bool result = pvrtexture::GenerateMIPMaps(texture, pvrtexture::EResizeMode::eResizeCubic, PVRTEX_ALLMIPLEVELS);
```
          It returns false.
UPDATE:
Sorry,it DOES work with RGBA textures.So the input texture must be RGBA always?

**Comment by PVRDevTech** [comment]
Legacy issue, said functions no longer exist. If there is a misunderstanding on this please reopen.
