### ISSUE TITLE
About GetPhysicalDeviceSparseImageFormatProperties cause runtime error.

### ISSUE THREAD

**Issue by heitaoflower** [powervr-graphics/Native_SDK#18]
When I build the sample of 02_vulkan_introducing_pvr_shell completed, I encountered a runtime error.

The error as follows:

`08-15 13:28:16.714 1975-2059/com.powervr.VulkanIntroducingPVRShell E/com.powervr.Example: VULKAN_LAYER_VALIDATION: invalid vkGetDeviceProcAddr(0x7f93fb0590, "vkGetPhysicalDeviceSparseImageFormatProperties") call
08-15 13:28:16.715 1975-2059/com.powervr.VulkanIntroducingPVRShell A/libc: E:/GIT/heitaohua/powervr-graphics-native-sdk/framework/PVRNativeApi/Vulkan/VulkanBindings.cpp:542: static bool vk::initVulkanDevice(VkDevice): assertion "GetPhysicalDeviceSparseImageFormatProperties" failed
08-15 13:28:16.715 1975-2059/com.powervr.VulkanIntroducingPVRShell A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2059 (Thread-7)`

What I want to say is the cause of the problem, Please note that VulkanBindings.cpp, The line `PVR_VULKAN_GET_DEVICE_POINTER(device, GetPhysicalDeviceSparseImageFormatProperties);` try to get the pointer of function, however, the function belongs to vulkan instance , not device. And  before this line, the function pointer has been obtained when the instance was initialized.

So to fix this issure just remove the line. Anyway please update the sdk files to prevent other people from encountering unnecessary problems.

**Comment by senthuran-lkn** [comment]
That is a good finding, I will fix it, thanks

**Comment by senthuran-lkn** [comment]
FIXED in 4.3
