### ISSUE TITLE
Gnome Horde demo breaks Vulkan's threading rules

### ISSUE THREAD

**Issue by garyjsweet** [powervr-graphics/Native_SDK#19]
When I run Gnome Horde with the threading validation layer present, after about 30 seconds, I see a a few threading errors (followed by a segv):

`THREADING(ERROR): object: 0x45cd88 type: 0 location: 0 msgCode: 1: THREADING ERROR : object of type NON_DISPATCHABLE_HANDLE is simultaneously used in thread -1636830128 and thread -1225728000`

My own debug appears to show that the same command pool is being used to both allocate and delete data from different threads simultaneously.

**Comment by senthuran-lkn** [comment]
Hi, really sorry for the late reply. What platform were you running?

**Comment by cylof22** [comment]
@garyjsweet How to enable the threading validation layer?

**Comment by gary-sweet** [comment]
When I originally did this the thread validation layer was called VK_LAYER_GOOGLE_threading.
Looking at LunarG's webpages ([here](https://vulkan.lunarg.com/doc/sdk/1.1.106.0/windows/layer_configuration.html) and [here](https://vulkan.lunarg.com/doc/sdk/1.1.106.0/windows/validation_layers.html)), it looks like that has now been superseded by VK_LAYER_KHRONOS_validation.

The LunarG pages should tell you how to enable the validation layers on your platform.

**Comment by PVRDevTech** [comment]
Hello,
@gary-sweet This issue has been fixed but unfortunately was never properly closed. Please reopen if my understanding is wrong on this.

@cylof22 As long as the layers are properly installed at the system (i.e. the LunarG SDK), the PowerVR SDK enables them explicitly (i.e. through code) in debug builds anyway so you should need no further action. To ensure that they are running, if you examine the log of any application created with PVRUtils (such as gnome horde and most other demos except the introducingXXX) you will see an information dump like :

```
INFORMATION: Supported Instance Layers:
INFORMATION: 	VK_LAYER_LUNARG_api_dump : Spec version [4198501], Implementation version [2]
INFORMATION: 	VK_LAYER_LUNARG_core_validation : Spec version [4198501], Implementation version [1]
INFORMATION: 	VK_LAYER_LUNARG_device_simulation : Spec version [4198501], Implementation version [1]
INFORMATION: 	VK_LAYER_LUNARG_parameter_validation : Spec version [4198501], Implementation version [1]
INFORMATION: 	VK_LAYER_GOOGLE_threading : Spec version [4198501], Implementation version [1]
INFORMATION: 	VK_LAYER_GOOGLE_unique_objects : Spec version [4198501], Implementation version [1]
INFORMATION: 	VK_LAYER_LUNARG_vktrace : Spec version [4198501], Implementation version [1]

```
