### ISSUE TITLE
GLES binaries removed from the latest release

### ISSUE THREAD

**Issue by sasmaster** [powervr-graphics/Native_SDK#22]
Any reason for that?

**Comment by senthuran-lkn** [comment]
We don't provide examples binaries on github page, only the source codes are available here, which you can build on your system. If you want pre-built binaries then I recommend downloading our SDK package from https://community.imgtec.com/developers/powervr/graphics-sdk/ which has the same contents with pre-built binaries and tools.

**Comment by sasmaster** [comment]
I am talking about glesv2 emulate lib. Not about the examples. You don't
provide one for windows in the latest release.

**Comment by senthuran-lkn** [comment]
Sorry for the misunderstanding, it is missing from the package. I will upload it. thanks

**Comment by senthuran-lkn** [comment]
Hi the libs are now pushed in to github..

**Comment by sasmaster** [comment]
Thanks!
