### ISSUE TITLE
CMake scripts to build PVR

### ISSUE THREAD

**Issue by rcdailey** [powervr-graphics/Native_SDK#24]
PowerVR developers: Would you be interested in CMake scripts I have written to build your code in this repository? The scripts are pretty simple and do not have any INSTALL logic, but they can be used to integrate your repository in to other downstream CMake projects to build targets like PVRUtils, PVRCore, etc.

**Comment by PVRDevTech** [comment]
Wow - really appreciate the time and effort. 

In an amazing stroke of coincidence, we are (literally!) a few days from publishing the next release, including full CMake support... We wanted to do that for some time now, and we have finished implementing it - we are now in the final testing phase.

There is a lot of restructuring going on in the current release. 

I would be really loath for your effort to go to waste, I would be quite happy to check out what you have done, potentially incorporate some of it if there is something we have missed or can improve our implementation.

**Comment by rcdailey** [comment]
Oh mine is pretty thrown-together. I only spent a few hours on it. It literally just builds static libraries of only a few of your utils and isn't tested on more platforms than Android (NDK), Linux x86, and Windows x86. So what you have is probably better than mine. I made the offer with the intention of cleaning up what I have and making it more useful for a general audience.

I'm happy to consume your scripts when you publish them. If the scripts could use more changes or require changes in order to fit my specific needs, I'm happy to make those changes and create one or more pull requests. If you'd be happy accepting those contributions in piecemeal then that would be great. Let me know and thanks for your quick response!

**Comment by senthuran-lkn** [comment]
Hi just to let you know that we have released our new SDK, branch 5.1, based on cmake. 
I mark this ticket as closed. 
Thanks.

**Comment by rcdailey** [comment]
Having looked at 5.2, there's some huge improvements needed to the current CMake support. I'm actively working on these improvements for you, so I'd appreciate it if you could reopen this issue. Here's the list:

* Use an actual target for the PowerVR SDK (this allows transitive includes & such)
* The framework projects are independent of each other right now, however this does not allow sharing of common PowerVR SDK targets. These will be included via `add_subdirectory()` so they can be accessed from anywhere.

The motivation for these changes is being able to add the PowerVR repo as a submodule and integrate it into existing downstream projects via `add_subdirectory`. This should expose all frameworks and libraries to consumers, so they can add them directly as link dependencies.

**Comment by rcdailey** [comment]
Also as a side topic, it would be great if you guys used a `master` branch for your releases, and instead of branches for each release, tag a specific commit on `master`.

**Comment by PVRDevTech** [comment]
Hi rcdailey,

Coincidentally we've been looking into a bunch of CMake changes over the last few weeks - primarily looking into the use of external projects for 3rd party dependencies but in general we've been tidying up some of our CMake usage in general.
When you say "use an actual target for the PowerVR SDK" - we intentionally don't use a generic target for the PowerVR SDK and instead rely on the user (our examples) to include the modules they specifically require. 
	As an example the demo OpenGLES/IntroducingPVRShell uses a different set of modules than Vulkan/Navigation2D so using a shared target wouldn't make sense here. 
Each of the examples currently uses add_subdirectory as appropriate to include the required set of framework modules/targets.
We've previously discussed breaking up the examples and framework into separate repos to allow this kind of usage to make a little more sense

We'd be very interested to see your changes though as there's definitely (a lot of) room for improvement - as you've seen our CMake support is quite new to the PowerVR SDK. Feel free to submit a pull request so we can take a look. For now I'll take a look through your fork.

As mentioned above we definitely appreciate the time and effort you're spending on this.

Out of curiosity how are you planning on making use of the PowerVR SDK - if you don't mind us asking?

Thanks,
James

**Comment by rcdailey** [comment]
> When you say "use an actual target for the PowerVR SDK" - we intentionally don't use a generic target for the PowerVR SDK and instead rely on the user (our examples) to include the modules they specifically require.
> As an example the demo OpenGLES/IntroducingPVRShell uses a different set of modules than Vulkan/Navigation2D so using a shared target wouldn't make sense here.

So I looked at these 2 examples, and the only real differences I see is that you include different `framework` libraries. However, none of these are interconnected so instead of the CMake targets being directly available to you, you have to go through some weird hoops to `add_subdirectory()` them prior to adding them as link dependencies.

However, what I have completely decouples the configuration of the `framework` targets from PowerVR SDK itself. Granted, this isn't too sophisticated, and may be incomplete as of right now since I'm not quite done yet, but really all I'm doing is wrapping some common properties in your `cmake/Common.cmake` into target. As an example, I have this in the root `CMakeLists.txt`:

```
add_library(PowerVR_SDK INTERFACE)
target_include_directories(PowerVR_SDK INTERFACE
    ${SDK_ROOT}/include
    ${SDK_ROOT}/framework
)

target_link_libraries(PowerVR_SDK INTERFACE ${EXTRA_LIBS})
```

With this, I made these changes to `framework/PVRCore` (Others will change as well, but just showing this one as an example):

```
set(source_files
    cameras/CameraKeyFrame.h
    cameras/FPSCamera.h
    cameras/TPSCamera.h
    commandline/CommandLine.h
    Errors.h
    glm.h
    IAssetProvider.h
    Log.h
    math/AxisAlignedBox.h
    math/MathUtils.h
    math/Plane.h
    math/Rectangle.h
    math/Rectangle3D.h
    pfx/Effect.h
    pfx/PFXParser.cpp
    pfx/PFXParser.h
    PVRCore.h
    RefCounted.h
    stream/Asset.h
    stream/AssetReader.h
    stream/AssetWriter.h
    stream/BufferStream.h
    stream/FilePath.h
    stream/FileStream.h
    stream/Stream.h
    strings/CompileTimeHash.h
    strings/StringFunctions.h
    strings/StringHash.h
    strings/UnicodeConverter.cpp
    strings/UnicodeConverter.h
    texture/MetaData.h
    texture/PixelFormat.h
    texture/PVRTDecompress.cpp
    texture/PVRTDecompress.h
    texture/Texture.cpp
    texture/Texture.h
    texture/TextureDefines.h
    texture/TextureHeader.cpp
    texture/TextureHeader.h
    texture/TextureLoad.h
    texture/TextureLoadAsync.h
    texture/TextureUtils.h
    textureio/FileDefinesBMP.h
    textureio/FileDefinesDDS.h
    textureio/FileDefinesKTX.h
    textureio/FileDefinesPVR.h
    textureio/FileDefinesTGA.h
    textureio/FileDefinesXNB.h
    textureio/PaletteExpander.cpp
    textureio/PaletteExpander.h
    textureio/TextureReaderBMP.cpp
    textureio/TextureReaderBMP.h
    textureio/TextureReaderDDS.cpp
    textureio/TextureReaderDDS.h
    textureio/TextureReaderKTX.cpp
    textureio/TextureReaderKTX.h
    textureio/TextureReaderPVR.cpp
    textureio/TextureReaderPVR.h
    textureio/TextureReaderTGA.cpp
    textureio/TextureReaderTGA.h
    textureio/TextureReaderXNB.cpp
    textureio/TextureReaderXNB.h
    textureio/TextureWriterPVR.cpp
    textureio/TextureWriterPVR.h
    textureio/TGAWriter.h
    Threading.h
    types/FreeValue.h
    types/GpuDataTypes.h
    types/Types.h
    Utils.h
)

if(WIN32)
    list(APPEND source_files
        Windows/WindowsResourceStream.h
    )
elseif(ANDROID)
    list(APPEND source_files
        Android/AndroidAssetStream.cpp
        Android/AndroidAssetStream.h
    )
elseif(APPLE)
    message("SET UP APPLE FOR PVRCORE")
endif()

add_library(PVRCore STATIC ${source_files})
target_include_directories(PVRCore PUBLIC ..)
target_compile_definitions(PVRCore PUBLIC
    $<$<CONFIG:Debug>:DEBUG=1>
    $<$<NOT:$<CONFIG:Debug>>:NDEBUG=1 RELEASE=1>
)
target_link_libraries(PVRCore PUBLIC pugixml PowerVR_SDK)
```

Notice at the bottom, I specify `PowerVR_SDK` as a link dependency, which transitively provides include directories, compile definitions, and link libraries. Opting for this instead of "global" properties via included file is the more modern way of doing things in CMake. By attaching all of the relevant properties to the targets themselves, you enable downstream libraries to more easy and more automatically inherit that information. It's also a lot easier than spreading `include()` commands everywhere.

> Each of the examples currently uses add_subdirectory as appropriate to include the required set of framework modules/targets.

This is a legacy way of using CMake and does not represent more modern techniques. This way of doing things has a few issues that I won't get into here. Sadly, it's hard to find good best practices guides for CMake. Most of what I've learned was hard to search for and a good bit of it came from the CMake developers themselves.

> We've previously discussed breaking up the examples and framework into separate repos to allow this kind of usage to make a little more sense

Maybe need some more detail here, but I don't see how this makes anything easier. If anything, separate repos in Git tend to add complexity, especially if submodules are involved. I think the way you have things structured right now is very close to how most open source projects do it. I think you've done things correctly as they stand, but again I am not familiar with everything about PVR SDK that you are.

> We'd be very interested to see your changes though as there's definitely (a lot of) room for improvement - as you've seen our CMake support is quite new to the PowerVR SDK. Feel free to submit a pull request so we can take a look. For now I'll take a look through your fork.

My work is a work in progress. My changes are pushed to `master` on my fork right now, so you can take an early peek at what I have if you want. The PR will be made when I have something more finalized. Worth noting in advance, however, that I can comfortably only refactor the parts I'm actually using. For example, I do not use Vulkan at all. I can try to make the CMake changes I think are required, but I won't have any method of testing those changes.

Could I work with you guys to come up with a test plan? Do you guys have a QA team that can help test? Or can the developers maybe try out the changes? Or even, maybe you guys would prefer to make those CMake changes yourself, using the OpenGLES ones as an example? Would love to work on a strategy here.

> As mentioned above we definitely appreciate the time and effort you're spending on this.

No problem!

> Out of curiosity how are you planning on making use of the PowerVR SDK - if you don't mind us asking?

We have a C++ application that utilizes PowerVR. Our primary platform is Android (API 15, API 17, and API 22), but we also support x86 Linux (for running unit tests) and Windows (for tooling that utilizes our engines). The Android devices obviously already have the EGL libraries under `/system/lib`. One Android platform in particular uses the PowerVR texture format (PVRTC). We use the framework libraries to load these texture files and push them into OpenGL. Other platforms have the same texture requirements (for backward compatibility). We only use the framework libs of the PowerVR SDK on the Android platform.

On Linux, we still initialize OpenGL because some of the code we unit test does call GL/EGL functions. However, it's a headless machine and we do not specifically need rendering functionality. However, on this platform, we still need the PVR SDK libraries to "simulate" EGL on this platform due to the linker requirements.

On Windows, we actively render via EGL (through PowerVR SDK) for our tools.

The reason for my CMake changes are that I do not want to have to deal with a lot of complex configuration when I pull in the PVR CMake project. The adhoc way of using CMake is to:

1. `add_subdirectory()` the project's root directory (and thus its root `CMakeLists.txt`)
1. Add the upstream targets via `target_link_libraries()` to pull in include directories, compile definitions, and link libraries as required by the upstream project itself. These properties are managed by the library maintainers (you, in this case).

However,  yours requires intimate knowledge (somewhat) of your CMake project structure. There are non-standard (from a pure CMake standpoint) requirements that must be followed (e.g. specific `*.cmake` files must be included). This requires a lot more investigation and configuration for the downstream project (me, in this case).

I know I've typed a lot, and I apologize for that. I wanted to be as thorough as possible for you. At the end of the day, the goal is to adapt what you have into the more modern way of using CMake, and using various idioms that people expect, which makes your library easier to integrate downstream as a dependency.

**Comment by PVRDevTech** [comment]
As you've suggested I think we should be making much better use of targets to avoid some of the "weird hoops" we're currently jumping through. 
We're going to have to carefully consider the inclusion of a PowerVR_SDK root target as you've shown as well as some of the other changes you've made to ensure that they meet our requirements as well as yours. 
For the most part what you're suggesting makes sense and in general we should be using more "modern" CMake techniques. As mentioned this was something we were already taking a look at internally :).

> We only use the framework libs of the PowerVR SDK on the Android platform

FYI you should be able to comfortably use the framework libs on desktop platforms as well as on Android for loading the same PVRTC textures which will then be automatically decompressed as appropriate. Not sure whether this may be of use to you but I thought I should mention it either way. 

> However, yours requires intimate knowledge (somewhat) of your CMake project structure. There are non-standard (from a pure CMake standpoint) requirements that must be followed (e.g. specific *.cmake files must be included). This requires a lot more investigation and configuration for the downstream project (me, in this case).

Totally agree with this and we'll investigate how best to fix this - we'll obviously take a look through your generously provided pull request :)

We're going to spend a little time looking into this and we'll get back to you.

**Comment by rcdailey** [comment]
Thanks for the positive feedback.

And just in case I wasn't clear, I by no means expect you to take my changes verbatim. I lack so much knowledge on your project, and to make it worse, this is probably just the distributable output of your actual repository, which might be structured completely differently. If anything, my changes might be useful as a reference, or a way to communicate my requirements. That's fine though.

> FYI you should be able to comfortably use the framework libs on desktop platforms as well as on Android for loading the same PVRTC textures which will then be automatically decompressed as appropriate. Not sure whether this may be of use to you but I thought I should mention it either way.

I apologize, I think I worded my initial statement incorrectly. I do use the framework libs on all platforms, but the PowerVR SDK libs I only link on Windows & Linux. Our specific build of Android AOSP has GL system libs that are loaded.

I'm available any time to help out. Let me know if I can do anything else for you.

**Comment by PVRDevTech** [comment]
Hi @rcdailey,

Sorry for going a little quiet on this issue (as well as the related pull request). We've made these changes internally and are working on releasing them as part of our 19.1 SDK release which is due anytime now.

Thanks again for reporting this to us as well as pointing us in the right direction with your pull request. Very much appreciated.

**Comment by rcdailey** [comment]
Sorry I didn't get back to you on this. Thanks for improving it and I'm glad my work helped out. I'll go ahead and close this.
