### ISSUE TITLE
Builds directory gone in 5.1: Where to get EGL lib & dll files?

### ISSUE THREAD

**Issue by rcdailey** [powervr-graphics/Native_SDK#25]
5.0 used to have the DLL files for libEGL and others. Those are gone in 5.1. Also I think 5.0 was missing libEGL.lib for linking and such. Is it possible to get these lib & dll files without downloading the SDK officially (e.g. through github only)?

**Comment by senthuran-lkn** [comment]
Hi, apologies for not responding to you earlier and thank you for bringing up this issue.  The libraries are checked in, it should be in the lib/Windows_x86_* folder. 
I'll close this issue
Thank you
