### ISSUE TITLE
Compilation failures on VS 2019

### ISSUE THREAD

**Issue by rcdailey** [powervr-graphics/Native_SDK#35]
`TextureHeader.h` in PVRCore fails to compile because it is missing an include for `<string>` (`std::string` is used in the header). Adding this line somewhere to the top fixes the issue:

```
#include <string>
```

**Comment by PVRDevTech** [comment]
Hi @rcdailey ,

Thanks for reporting this issue to us! I've fixed this in commit f394bdd. AS you suggested simply adding an include for <string> fixed the compilation issue.
