### ISSUE TITLE
GnomeHord will crash after the first frame is rendered

### ISSUE THREAD

**Issue by cylof22** [powervr-graphics/Native_SDK#36]
GnomeHord will crash on Android 9.0 because of infinite loop in renderFrame. The infinite  loop is caused by the zero return value of _tilesToDrawQ.consumeMultiple(_deviceResources->drawQconsumerToken, results, 256));

**Comment by PVRDevTech** [comment]
Hi @cylof22, is there any additional information you can provide to help us reproduce the issue as it looks like we will need to dig for it, face value, it does not appear as if there are should be an infinite loop _(there as **consumeMultiple** is a blocking call, so should wait until an item returns unless the queue is being destroyed, which should not be the case in the first frame)_.

**Comment by cylof22** [comment]
@PVRDevTech Sorry for the confusion. The demo is ok on Android 7.0. After updating my system from Huawei, the demo crash on Android 9.0. 

After debugging the demo, I find that the crash is caused by an exception: art_sigsegv_fault. The exception is triggered on another thread, and the stack is like this: 
`syscall 0x0000007b78b1f2ec
__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) 0x0000007b78b22ea8
sem_wait 0x0000007b78b2d818
moodycamel::details::mpmc_sema::Semaphore::wait() blockingconcurrentqueue.h:178
moodycamel::details::mpmc_sema::LightweightSemaphore::waitWithPartialSpinning() blockingconcurrentqueue.h:230
moodycamel::details::mpmc_sema::LightweightSemaphore::wait() blockingconcurrentqueue.h:287
bool moodycamel::BlockingConcurrentQueue<TileProcessingResult, moodycamel::ConcurrentQueueDefaultTraits>::wait_dequeue<TileProcessingResult>(moodycamel::ConsumerToken&, TileProcessingResult&) blockingconcurrentqueue.h:789
pvr::LockedQueue<TileProcessingResult>::consume(moodycamel::ConsumerToken&, TileProcessingResult&) Threading.h:403
GnomeHordeTileThreadData::doWork() VulkanGnomeHorde.cpp:933
GnomeHordeWorkerThread::run() VulkanGnomeHorde.cpp:458
decltype(*(std::__ndk1::forward<GnomeHordeTileThreadData*>(fp0)).*fp()) std::__ndk1::__invoke<void (GnomeHordeWorkerThread::*)(), GnomeHordeTileThreadData*, void>(void (GnomeHordeWorkerThread::*&&)(), GnomeHordeTileThreadData*&&) type_traits:4228
void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeTileThreadData*, 2ul>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeTileThreadData*>&, std::__ndk1::__tuple_indices<2ul>) thread:348
void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeTileThreadData*> >(void*) thread:358
__pthread_start(void*) 0x0000007b78b83554
__start_thread 0x0000007b78b241a4`.

**Comment by PVRDevTech** [comment]
Hi @cylof22 , while I cannot reproduce the issue here (I do not have this particular phone and another Android 9.0 platform I have tried does not reproduce), the stacktrace you provided points to the mulithreaded queue library we had been using.
I think it is worth it for me to attempt to update it (not completely straight forward as the original library had some modifications, hence we were bundling it) and come back to you with possibilities.

**Comment by PVRDevTech** [comment]
Hi @cylof22, would you mind running a test overwriting the attached files? It's just the newest version of the concurrent queue(4 files including the 2 readmes) and a modified version of the file containing our wrapper of the queue (another file).
You just need to extract this one in the SDK folder and it should overwrite the correct files. If it solves your issue I will push the modification in.

**Comment by cylof22** [comment]
@PVRDevTech I checked your patch. It doesn't work. The expection 'art_sigsegv_fault' still happens. See the follow stack: 

syscall 0x0000007b78b1f2f0

__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) 0x0000007b78b22ea8

__sem_timedwait(sem_t*, timespec const*, bool) 0x0000007b78b2d94c

moodycamel::details::mpmc_sema::Semaphore::timed_wait(unsigned long) 

blockingconcurrentqueue.h:226

moodycamel::details::mpmc_sema::LightweightSemaphore::waitWithPartialSpinning(long) 

blockingconcurrentqueue.h:282

moodycamel::details::mpmc_sema::LightweightSemaphore::wait(long) 

blockingconcurrentqueue.h:362

bool moodycamel::BlockingConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::wait_dequeue_timed<int>(moodycamel::ConsumerToken&, int&, long) blockingconcurrentqueue.h:814

pvr::LockedQueue<int>::consume(moodycamel::ConsumerToken&, int&) Threading.h:430

GnomeHordeVisibilityThreadData::doWork() VulkanGnomeHorde.cpp:1012

GnomeHordeWorkerThread::run() VulkanGnomeHorde.cpp:458

decltype(*(std::__ndk1::forward<GnomeHordeVisibilityThreadData*>(fp0)).*fp()) std::__ndk1::__invoke<void (GnomeHordeWorkerThread::*)(), GnomeHordeVisibilityThreadData*, void>(void (GnomeHordeWorkerThread::*&&)(), GnomeHordeVisibilityThreadData*&&) type_traits:4228

void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeVisibilityThreadData*, 2ul>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeVisibilityThreadData*>&, std::__ndk1::__tuple_indices<2ul>) thread:348
void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (GnomeHordeWorkerThread::*)(), GnomeHordeVisibilityThreadData*> >(void*) thread:358
__pthread_start(void*) 0x0000007b78b83554
__start_thread 0x0000007b78b241a4.

 I need to check the other manufacture's device, like xiaomi to make sure the problem is not special for Haiwei.

**Comment by graptis** [comment]
Hi @cylof22 , do you have any further comments/requests on this? We still cannot reproduce it. 
Thanks.

**Comment by cylof22** [comment]
@graptis  This bug can only be reproduced on my phone. Please close it now. Thanks!
