### ISSUE TITLE
Win XP support

### ISSUE THREAD

**Issue by larsn777** [powervr-graphics/Native_SDK#4]
Hello,
I'm using your sdk libraries on Windows. But then I've decided to compile my project at winxp I faced with the fact that those dlls (libegl.dll) couldn't be used at XP (they are linked with new versions of windows system libraries).
Could please help me with my problem. For example could you give me a link to a XP compatible libraries. I realy don't want to hijack your current libs for XP)) 
Thanks

**Comment by KevinSunIMG** [comment]
Hi larsn777,
The SDK only support Windows 7 and newer (X86 & X64).
You can find more detail information in following web page:
https://community.imgtec.com/developers/powervr/graphics-sdk/

Thanks,
Kevin
