### ISSUE TITLE
[BUG]new sdk does not work on macos anymroe

### ISSUE THREAD

**Issue by dguimard** [powervr-graphics/Native_SDK#53]
## Environment

* SDK version: 
* Operating System/Device:

**Comment by omarzohdi** [comment]
Hi @dguimard,

Could you please provide more details regarding the issue you're facing:

- What tag of the PowerVR SDK are you working with? 
- What macOS version are you using?
- What exactly is the issue you're facing?

Thanks,
Omar.

**Comment by omarzohdi** [comment]
I'll be closing the issue as there's not enough information to ascertain what exactly the bug is and how to reproduce it. Feel free to reopen it if you deem it necessary.
