### ISSUE TITLE
[BUG] Update Vulkan validation layers to the unified VK_LAYER_KHRONOS_validation layer 

### ISSUE THREAD

**Issue by hevrard** [powervr-graphics/Native_SDK#54]
## Description

The Android Vulkan validation layers provided in https://github.com/powervr-graphics/Native_SDK/tree/master/external/validation_layers/jniLibs are now a bit old. In particular, since March 2019, the `VK_LAYER_KHRONOS_validation` unified layer supersedes the series of historical validation layers.

See https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/LAYER_CONFIGURATION.md#validation-layer-overview

This layer is now available through github releases at:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/sdk-1.2.135.0

## Repro steps

Build the app for Android by default. The Gradle setup picks the layers shipped in the NDK, or the ones provided in external/validation_layers, both of which are old.

## Environment

n/a

## Additional Info
This may require to change the list of layer names queried by the Vulkan samples.
It will also be worth checking if the up-to-date, unified layer leads to new warning/errors on the samples.

**Comment by graptis** [comment]
Hi @hevrard, thanks for the report. I took a very quick look, this makes sense, we will work to integrate android layer releases instead of the pre-packaged ones.

**Comment by graptis** [comment]
Updated on 20.1 release.
