### ISSUE TITLE
[BUG]Mac OS Catalina: CodeSign failed on ligEGL.dylib

### ISSUE THREAD

**Issue by AllonJunior** [powervr-graphics/Native_SDK#56]
## Description
On Mac OS Catalina, Xcode 11.5
powerVR libraries can be built well, but there will be a `CodeSign error` when building the examples.Like below
`/powerVR-build/bin/Debug/OpenGLESHelloAPI.app: code object is not signed at all
In subcomponent: /powerVR-build/bin/Debug/OpenGLESHelloAPI.app/Contents/Frameworks/libEGL.dylib
Command /usr/bin/codesign failed with exit code 1`

## Environment

* SDK version: R19.2-v5.4
* Operating System/Device: Mac OS Catalina, Xcode 11.5, base SDK Mac OSX 10.15

**Comment by nobitavn89** [comment]
I have same issue when building OpenGL ES Examples in my Mac although a running file can be found at
build/bin/Debug folder.
`
/Users/tuanminhnguyen/gitprojects/Native_SDK/build/bin/Debug/OpenGLESHelloAPI.app: code object is not signed at all
In subcomponent: /Users/tuanminhnguyen/gitprojects/Native_SDK/build/bin/Debug/OpenGLESHelloAPI.app/Contents/Frameworks/libEGL.dylib
Command /usr/bin/codesign failed with exit code 1`

**Comment by omarzohdi** [comment]
Hi @nobitavn89, @AllonJunior, 

Sorry for the delayed reply. Due to the current situation our release was drastically delayed. The issue should be fixed in the latest release 3f88b0f. I'll close the issue but feel free to reopen if the bug still persists for you.
