### ISSUE TITLE
[BUG] Pre-built SDKs no longer available for download.

### ISSUE THREAD

**Issue by MarkCallow** [powervr-graphics/Native_SDK#57]
## Description

I had been downloading an SDK to my CI  builds from https://powervr-graphics.github.io/. Those are no longer available.

## Repro steps

Just look on https://powervr-graphics.github.io/. There are no binaries available any more.

## Environment

* SDK version: n/a 
* Operating System/Device: n/a 

## Additional Info
I've tried to download using the link from the Imagination web site:

```
curl -O https://www.imgtec.com/download/windows-installer-pvrvframe/?dlm-dp-dl-force=1
```
but I get 0 bytes back. How can I download it via curl rather than a web browser?

I debated whether to make this an RFI or a bug. A bug won, since you used to have these and their removal broke my CI builds.

**Comment by nobitavn89** [comment]
It seems that IMG didn't release pre-built libs with their SDK in latest version.
If you don't care about the versions, I think this one is still available
https://www.imgtec.com/developers/powervr-sdk-tools/legacy-downloads/

**Comment by MarkCallow** [comment]
Thanks for the suggestion but I get the same problem with the legacy links as with the `pvrframe` link.

```
$ curl -o PVRSDKSetup.exe "https://www.imgtec.com/download/windows-installer-powervr-tools-and-sdk/?version=2019-r2"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
mark:~ $ echo $?
0
```

No data and no error. How can I download these things non-interactively?

**Comment by nobitavn89** [comment]
oh, sorry. I didn't know that you want to download it non-interactively.

**Comment by graptis** [comment]
Hi Mark, thanks for the reports. I would like to clarify exactly which binaries you are referring to.
If you are talking about the prebuild binaries of the examples (OGLESParticleSustem.exe etc.) , we stopped releasing them mostly for download size. If you have a use-case that needs it, we can reconsider. Ditto for the prebuild binaries of framework libraries, since most people would integrate at the CMake- or gradle- level, we decided to skip them for size and because we cannot anticipate every single platform imaginable (Ubuntu versions), but again please let us know what you need so we can give you a more informed answer.
On the other hand, If you are talking about libraries we package as binaries with the SDK (PVRVFrame and PVRScope), they should be there.
As far as the curl method of downloading, I think this is a matter of it breaking due to a redirection, a colleague is looking for a solution.

**Comment by MarkCallow** [comment]
I just need the emulator libraries for Windows: libGLES_CM.{lib,dll}, libGLESv2.{lib,dll} and libEGL.{lib,dll}. I was previously downloading these from the pre-built SDK you had on GitHub. Now I am tying to download either PVRFrame or an earlier SDK from imgtec.com to install in the CI build.

I appreciate you looking into why the curl download is not working.

**Comment by omarzohdi** [comment]
Hi @MarkCallow the PVRVFrame libraries can be found right here in the Native_SDK github repo in [/lib/[PLATFORM]](https://github.com/powervr-graphics/Native_SDK/tree/master/lib/). If you need to work with Native_SDK and require PVRVFRame I'd recommend using the ones in that folder, which should be included automatically when running cmake.

if you need to use the PVRVFrame libraries for something else other the the Native_SDK I'd recommend running the curl command on their github url to get the latest released libraries directly from github:

```
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libEGL.dll
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libEGL.lib
```
```
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libGLES_CM.dll
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libGLES_CM.lib
```
```
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libGLESv2.dll
curl -L -O https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/libGLESv2.lib
```
Note: You should modify these commands to point to the appropriate folder for the platform you're working on.

Hope this helps.
Omar.

**Comment by MarkCallow** [comment]
Thank you @omarzohdi . Those URLs work and are just what I needed. I don't know how I missed them when I was looking on GitHub after the targets of URLs from githubusercontent, that I had been using, disappeared. I didn't find any binaries.
