### ISSUE TITLE
[BUG] PVRTexTool 4.24 image viewer too dark

### ISSUE THREAD

**Issue by graptis** [powervr-graphics/Native_SDK#60]
## Description

PVRTexTool to 4.24 displays all images as too dark, as gamma correction is not applied to textures before being displayed.

## Repro steps

* Open a source format (jpg, png, etc) image, or a pvr image generated with 4.24 or later on the viewer. They appear darker than they actually are.

## Environment

* SDK version: R20.1
* Operating System/Device: All

## Additional Info
This appears to be an issue that was caused by 19.2 version incorrectly generating SRGB images even when they were supposed to be Linear, so the viewer was compensating by darkening the images. Since the texture encoding was fixed, images consistently appear darker.

**Comment by graptis** [comment]
Adding this issue here for tracking. A fix is implemented for 20.2 as the whole viewer is overhauled.

**Comment by YukiNero39** [comment]
when will the fix be available?

**Comment by graptis** [comment]
The next release is currently planned around September.

**Comment by omarzohdi** [comment]
As mentioned in #59 the issue was fixed in the 20.2 release. I'm closing the issue as it refers to v4.24.
