### ISSUE TITLE
[BUG] sdkver.h: Version is still 5.1

### ISSUE THREAD

**Issue by riffmasterv7** [powervr-graphics/Native_SDK#62]
**#define PVRSDK_VERSION "5.1"**
#define PVRSDK_BUILD "20.1@5715297"
#define PVRVERSION_MAJ "20"
#define PVRVERSION_MIN "1"
#define PVRVERSION_BRANCH "201"
#define PVRVERSION_BRANCH_DEC "20.1"
#define PVRVERSION_BRANCH_NAME "REL/20.1"
#define PVRVERSION_BUILD "5715297"
#define PVRVERSION_BUILD_HI "571"
#define PVRVERSION_BUILD_LO "5297"

**Comment by omarzohdi** [comment]
Hi @riffmasterv7,

Thanks for the bug report! The PVRSDK_VERSION was fixed in the latest release of the SDK 3f88b0f.

Cheers!
