### ISSUE TITLE
Optimising the PostProcessing/FragShader.fsh 

### ISSUE THREAD

**Issue by senthuran-ukr** [powervr-graphics/Native_SDK#63]
I see that in the vulkan postfragment Fragshader,  when calculating the oFilter you are doing log2 and exp2 for each fragments/frame. Instead calculate the final exposure value in the CPU and pass it to the push constant(Save GPU cycle).
Therefore we only recalculate the "exposure" value when we need to when the user input changes in the application. 
 
OLD VERSION
```
layout(push_constant) uniform pushConstantsBlock{
	mediump float linearExposure;
	mediump float threshold;
};
......
mediump float exposure = log2(max(linearExposure, 0.0001f));
exposure -= threshold;
exposure = exp2(exposure);
oFilter = luma(exposure * oColor.rgb);;
```

SIMPLER & OPTIMISED VERSION
```
layout(push_constant) uniform pushConstantsBlock{
	mediump float exposure;
};
oFilter = luma(exposure * oColor.rgb);;
```
https://github.com/powervr-graphics/Native_SDK/blob/master/examples/Vulkan/PostProcessing/FragShader.fsh

HOPE IT HELPS. 
MERRY CHRISTMAS.

**Comment by dasco597** [comment]
Thanks Senthuran!

This change will be going into the upcoming release.

A tad late, but merry christmas to you too!
