### ISSUE TITLE
[QUESTION] Can the UIRenderer display sliders and/or other interactive elements?

### ISSUE THREAD

**Issue by Xeais** [powervr-graphics/Native_SDK#65]
Or would, for example, [Dear ImGui](https://github.com/ocornut/imgui) have to be used for this?

After skimming the corresponding code I would negate the title question; have I missed something?

**Comment by omarzohdi** [comment]
Hi, Xeais, The UIRenderer module in the framework is mostly for basic UI elements like text and images for sliders and more interactive elements I'd recommend using for ImGui.
Cheers!

**Comment by Xeais** [comment]
> Hi, Xeais, The UIRenderer module in the framework is mostly for basic UI elements like text and images for sliders and more interactive elements I'd recommend using for ImGui.
> Cheers!

Thank you for your answer; so my guess was right. 

In this case, would you rather extend the UIRenderer or give ImGui a seperate renderer?

**Comment by omarzohdi** [comment]
Hi, Xeais,

Personally, I'd give ImGui a separate renderer to implement the kind of functionality you've mentioned. I don't believe there should be any issue in have ImGui as a separate renderer along with UIRenderer. You should be able to implement sliders pretty easily.

On a side note, we currently don't have plans to support ImGui directly in our framework or to expand the functionality of UIRenderer, at least not for the upcoming release (should be available in the coming weeks). However, I want to pass the feedback along to the rest of the team and we'll have a discussion on how to tackle this kind of functionality going forward.

Cheers!

**Comment by Xeais** [comment]
Hi Omar,

Thank you for your enlightening answer; it is good to know that a separate renderer alongside UIRenderer shouldn't cause any conflicts.

Thank you, again, for the release date information (always valuable) and for passing the idea on to the rest of the team. As I was going through the associated documentation (nice job!), only the lack of the mentioned UI functionality struck me somewhat negatively, since this well made framework is otherwise quite complete.

Don't you happen to have a something like a Discord server for this project?

Regards!

**Comment by omarzohdi** [comment]
Hi, Xeais, 

Sorry for the late reply, glad I could be of help. We don't have a Discord server and don't have immediate plans to start one but I'll float the idea internally and see if that can be changed.

I'll close the issue for now but if you have any other questions please don't hesitate to ask!

Regards,
Omar.
