### ISSUE TITLE
[FEATURE REQUEST] WSL2 support on windows

### ISSUE THREAD

**Issue by luffydream** [powervr-graphics/Native_SDK#83]
## Description

Recently I want to use PowerVR.
 I want to know whether PowerVR support WSL On win11
Thank you so much

**Comment by AlejandroCosin** [comment]
Hi luffydream,

Thanks for your message.

Unfortunately, WSL only supports GPU hardware acceleration for some very specific cases like running CUDA. for general purpose 3D graphics, you will need to rely on emulators like SwiftShader or Angle.

Best regards,
Alejandro

**Comment by luffydream** [comment]
Thank you. I have compiling under WSL now. Most of cases could work normally. But some gl ext do not support . But I think this is enough for me now. I will try SwiftShader and Angle.
